### ISSUE TITLE
Automated tests from Red Hat

### ISSUE THREAD

**Issue by tcerna** [rear/rear-integration-tests#1]
Hi, 
I'm QE from Red Hat and I'm testing rear in RHEL-6 and RHEL-7.
I created several automated tests in bash with using beakerlib. These tests check creation of rescue and backup, content of iso file and functionality of checklayout.
What tests do you have? Are you interested in my work?
Regards,
Tereza Černá

**Comment by schlomo** [comment]
Wow! This is really great!

Yes - we would be most interested in those tests. Could you send us a pull request here?

**Comment by tcerna** [comment]
This is fixed by PR #2

**Comment by phracek** [comment]
@tcerna Go ahead with this awesome aproach. That's a way how the open source project should work. We as a Red Hat has to collaborate.

**Comment by gdha** [comment]
@phracek @tcerna what is the content of `root.files`? I'm using the `beakerlib` in my **rear-automed-testing** (https://github.com/gdha/rear-automated-testing) environment now. I also noticed that we need to install `rhts` (from https://github.com/beaker-project/rhts), but I couldn't find a RPM package of it.

In my project you will not yet find any tests, as I do still some research before I inject it - but I could use some help. We are preparing e rear-2.0 version which would be nice to replace rear-1.17.2 in RHEL.

@schlomo @jsmeix
By the way - I can now do a full cycle of mkbackup/recover complete unattended - which I will demonstrate at Fosdem 2017 in https://github.com/gdha/backup-disaster-recovery-devroom-fosdem-2017 devroom.

**Comment by tcerna** [comment]
@gdha What is root.files? It is content of / or /root ?
```
# ls /
bin   dev  home  lib64       media  opt   root  sbin  sys  usr
boot  etc  lib   lost+found  mnt    proc  run   srv   tmp  var

# # ls -la /root
total 256
dr-xr-x---.  5 root root   4096 Jan 20 06:42 .
dr-xr-xr-x. 18 root root   4096 Jan 20 06:42 ..
-rw-------.  1 root root   1521 Jul 17  2014 anaconda-ks.cfg
-rw-r--r--.  1 root root     18 Dec 28  2013 .bash_logout
-rw-r--r--.  1 root root    176 Dec 28  2013 .bash_profile
-rw-r--r--.  1 root root    630 Jul 17  2014 .bashrc
-rw-r--r--.  1 root root    100 Dec 28  2013 .cshrc
-rw-r--r--.  1 root root     11 Jan 20 06:23 install.time
-rw-------.  1 root root     77 Mar 25  2015 .lesshst
drwxr-xr-x.  2 root root   4096 Jul 17  2014 .lotr
-rw-r--r--.  1 root root 191725 Jul 17  2014 penguin-install.log
-rwxr-xr-x.  1 root root    622 Jan 20 06:03 set-hostname
drwx------.  2 root root   4096 Jun 10  2015 .ssh
-rw-r--r--.  1 root root    129 Dec 28  2013 .tcshrc
-rw-------.  1 root root   5789 Jan 20 06:42 .viminfo
```

You can try to install rhts-test-env, rhts-test-devel, rhts-test-python packages. Maybe it will help.

**Comment by gdha** [comment]
@tcerna Thanks for the reply - in the meantime I made a subset package of rhts-test-env, called rear-rhts which I use in the rear-automated-testing project

**Comment by psklenar** [comment]
Hello,
I noticed that there is some ansible playbook with preparation of hypervisor but not starting the tests. Is there any way how can I start it, or do you have any recommendation how internal testsuite could look like?

**Comment by gdha** [comment]
@psklenar See my other project https://github.com/gdha/rear-automated-testing where the tests can be used. See also the video made at Fosdem: https://fosdem.org/2017/schedule/event/backup_dr_automated_testing/
Around 19 minutes I'm taking about the test scripts.
